language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots

install:
  - sudo apt-get install -y libsdl2
  - sudo apt-get install -y libsdl2-image
  - sudo apt-get install -y libsdl2-mixer

script: make clean all
