language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq -y libsdl2-dev
  - sudo apt-get install -qq -y libsdl2-image-dev
  - sudo apt-get install -qq -y libsdl2-mixer-dev
  - sudo apt-get install -qq -y g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script: make all
