language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update

install:
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libsdl2-image-dev
  - sudo apt-get install -y libsdl2-mixer-dev

script: make clean all
