language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libsdl2-image-dev
  - sudo apt-get install -y libsdl2-mixer-dev

script: make clean all
